export const QUERY_MAPPING = {
  SCHOOL_DASHBOARD: "SCHOOL_DASHBOARD",
  SCHOOL_RESPONSIBLE_PAGINATE: "SCHOOL_RESPONSIBLE_PAGINATE",
  SCHOOL_STUDENT_PAGINATE: "SCHOOL_STUDENT_PAGINATE",
  SCHOOL_COURSE_PAGINATE: "SCHOOL_COURSE_PAGINATE",
} as const;
